version: '3'
services:
  app:
    image: back-tech-task-app
    container_name: back-tech-task-app
    build:
      context: ./
    volumes:
      - ./app:/src
    ports:
      - "3000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: development
    command: >
      bash -c "npm install &&
      npm install -g nodemon &&
      npm run watch"
    depends_on:
      - database

  database:
    image: postgres:12.3
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: development
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
