version: '3'
services:
  app:
    image: back-tech-task-app
    container_name: back-tech-task-app
    build:
      context: ./
    volumes:
      - ./app:/src
    ports:
      - "3000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: development
    command: >
      bash -c "npm install &&
      npm install -g nodemon sequelize-cli &&
      npm run watch"
    depends_on:
      - database
  database:
    image: postgres:12.3
    environment:
      POSTGRES_DB: development
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      -   database
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'
